databases:
  - name: hussein
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 -m kisan
    region: frankfurt
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: MUST_JOIN
        sync: false
      - key: OWNER
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: hussein
          property: connectionString   
    autoDeploy: false
